import './src/route/index.js'
import './src/accordion-slider.js'
import './src/characters-remaining.js'
import './src/content-loader.js'
import './src/json-syntax.js'
import './src/table-sort.js'
import './src/tool-tip.js'
import './src/touch-swipe.js'
