import '../../src/index.js'
import './characters-remaining.spec.js'
import './content-loader.spec.js'
import './route/index.spec.js'
import './table-sort.spec.js'
import './tool-tip.spec.js'
import './touch-swipe.spec.js'
